services:
    filegator:
        image: filegator/filegator:latest
        container_name: filegator
        environment:
            - TZ=${TIMEZONE:-Etc/UTC}
        volumes:
            - ${COMMON_STORAGE?error}:/var/www/filegator/repository
        ports:
            - 8084:8080
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.filegator.rule=Host(`filegator.${MAIN_ENDPOINT?error}`)"
            - "traefik.http.routers.filegator.entrypoints=web"
            - "traefik.http.services.filegator.loadbalancer.server.port=8080"
            - "traefik.docker.network=traefik-net"
        restart: unless-stopped
        networks:
            - traefik-net

networks:
    traefik-net:
        external: true
