services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - UMASK=${UMASK?error}
      - TZ=${TIMEZONE:-Etc/UTC}
    ports:
      - "8191:8191"
    volumes:
      - "${COMMON_STORAGE?error}/config/flaresolverr:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
      - "traefik.docker.network=traefik-net"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

