services:
    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        container_name: homarr
        restart: unless-stopped
        environment:
            - TZ=${TIMEZONE:-Etc/UTC}
            - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY?error}
        volumes:
            - "${COMMON_STORAGE?error}/config/homarr/appdata:/appdata"
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "7575:7575"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.homarr.rule=Host(`${MAIN_ENDPOINT?error}`)"
            - "traefik.http.routers.homarr.entrypoints=web"
            - "traefik.http.services.homarr.loadbalancer.server.port=7575"
            - "traefik.docker.network=traefik-net"
        networks:
            - traefik-net

networks:
    traefik-net:
        external: true
